# This file contains a registry of engine content files that are accessible by users. This file is manually maintained,
# and should not be touched
Content:
  Fonts:
    Comfortaa:
      Comfortaa-Bold.ttf: Asset_Font
      Comfortaa-Light.ttf: Asset_Font
      Comfortaa-Regular.ttf: Asset_Font
  Music:
    Jazz:
      bensound-romantic.mp3: Asset_Sound
  SFX:
    whistle.wav: Asset_Sound
  Sprites:
    Interface:
      Buttons:
        Choice_Button_Normal.png: Asset_Image
        Choice_Button_Hover.png: Asset_Image
        Choice_Button_Clicked.png: Asset_Image
        Menu_Button_Normal.png: Asset_Image
        Menu_Button_Hover.png: Asset_Image
        Menu_Button_Clicked.png: Asset_Image
      Dialogue:
        Dialogue_Frame.png: Asset_Image
    Placeholder.png: Asset_Image
    Orientation_Lines_1280x720.jpg: Asset_Image