# Type: Project_Settings
# Created with HBEditor v0.1

Game:
  title: Project Name
  author: Project Author
  company: Company
  starting_scene: ""
Window:
  resolution: 0
  resolution_options:
  - - 1280
    - 720
  - - 1920
    - 1080
Sprite:
  background_z_order: -9999
  z_order: 0
  center_align: true
Interactable:
  z_order: 100
  center_align: true
Text:
  size: 24
  color:
  - 255
  - 255
  - 255
  font: ENGINE_FILES/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  z_order: 100
  center_align: true
Button:
  sprite: ENGINE_FILES/Content/Sprites/Interface/Buttons/Menu_Button_Normal.png
  sprite_hover: ENGINE_FILES/Content/Sprites/Interface/Buttons/Menu_Button_Hover.png
  sprite_clicked: ENGINE_FILES/Content/Sprites/Interface/Buttons/Menu_Button_Clicked.png
  text_size: 16
  text_color:
  - 255
  - 255
  - 255
  font: ENGINE_FILES/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  text_z_order: 101
  text_center_align: true
  button_z_order: 100
  button_center_align: true
Dialogue:
  text_speed: 5
  speaker_text_position:
  - 0.25
  - 0.705
  speaker_text_size: 32
  speaker_text_color:
  - 253
  - 253
  - 253
  speaker_font: ENGINE_FILES/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  speaker_z_order: 200
  speaker_center_align: true
  dialogue_text_position:
  - 0.1
  - 0.77
  dialogue_text_size: 24
  dialogue_text_color:
  - 253
  - 253
  - 253
  dialogue_font: ENGINE_FILES/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  dialogue_wait_for_input: true
  dialogue_z_order: 200
  dialogue_center_align: false
  dialogue_frame_sprite: ENGINE_FILES/Content/Sprites/Interface/Dialogue/Dialogue_Frame.png
  dialogue_frame_z_order: 100
  dialogue_frame_center_align: true
  dialogue_frame_position:
  - 0.5
  - 0.8
Pause Menu:
  data_file: ENGINE_FILES/Content/Objects/Interface/PauseMenu/Test_Pause_Menu_01.yaml
Scene Transitions:
  speed: 150
  z_order: 9999
Choice:
  button_sprite: ENGINE_FILES/Content/Sprites/Interface/Buttons/Choice_Button_Normal.png
  button_sprite_hover: ENGINE_FILES/Content/Sprites/Interface/Buttons/Choice_Button_Hover.png
  button_sprite_clicked: ENGINE_FILES/Content/Sprites/Interface/Buttons/Choice_Button_Clicked.png
  button_text_size: 24
  button_text_color:
  - 204
  - 255
  - 255
  button_font: ENGINE_FILES/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  button_text_z_order: 101
  button_text_center_align: true
  button_z_order: 100
  button_center_align: true
