# Type: Project_Settings
# Created with HBEditor v0.1

Game:
  title: Project Name
  author: Project Author
  company: Company
  starting_scene: ""
Window:
  resolution: 0
  resolution_options:
  - - 1280
    - 720
Text:
  size: 24
  color:
  - 255
  - 255
  - 255
  font: HBEngine/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  z_order: 100
  center_align: true
  wrap_bounds:
  - 0.2
  - 0.2
Button:
  sprite: HBEngine/Content/Sprites/Interface/Buttons/Menu_Button_Normal.png
  sprite_hover: HBEngine/Content/Sprites/Interface/Buttons/Menu_Button_Hover.png
  sprite_clicked: HBEngine/Content/Sprites/Interface/Buttons/Menu_Button_Clicked.png
  z_order: 10001
  font: HBEngine/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
Dialogue:
  transition_type: "None"
  transition_speed: 500
  speaker_text_position:
  - 0.262
  - 0.703
  speaker_text_size: 32
  speaker_text_color:
  - 253
  - 253
  - 253
  speaker_text_font: HBEngine/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  speaker_text_z_order: 10000
  speaker_text_center_align: true
  speaker_text_wrap_bounds:
  - 0.25
  - 0.05
  dialogue_text_position:
  - 0.1
  - 0.75
  dialogue_text_size: 24
  dialogue_text_color:
  - 253
  - 253
  - 253
  dialogue_text_font: HBEngine/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  dialogue_text_z_order: 10000
  dialogue_text_center_align: false
  dialogue_text_wrap_bounds:
  - 0.8
  - 0.16
  dialogue_frame_sprite: HBEngine/Content/Sprites/Interface/Dialogue/Dialogue_Frame.png
  dialogue_frame_z_order: 9999
  dialogue_frame_center_align: true
  dialogue_frame_position:
  - 0.5
  - 0.8
  choice_button_sprite: HBEngine/Content/Sprites/Interface/Buttons/Choice_Button_Normal.png
  choice_button_sprite_hover: HBEngine/Content/Sprites/Interface/Buttons/Choice_Button_Hover.png
  choice_button_sprite_clicked: HBEngine/Content/Sprites/Interface/Buttons/Choice_Button_Clicked.png
  choice_button_text_size: 24
  choice_button_text_color:
  - 204
  - 255
  - 255
  choice_button_font: HBEngine/Content/Fonts/Comfortaa/Comfortaa-Regular.ttf
  choice_button_z_order: 10001
Pause Menu:
  data_file: HBEngine/Content/Objects/Interface/PauseMenu/Test_Pause_Menu_01.yaml
Scene Transitions:
  speed: 150
  z_order: 9999
