# Due to the way actions are designed, it's difficult to detect the data that they may require. In order to create
# a common, central place for the editor to know the requirements of each action, this file serves to list them out
#
# <category>:
#  - icon: <icon_path> (Icon in the editor content dir to use for the menu icon)
#  - options:
#    - display_name: <str> (Visible in Editor)
#      action_name: <str>> (Found in the engine actions)
#      requirements:
#       -  name: <str> (The name of the parameter)
#          type: <data_type> (A python data type)
#          default: <contextual_type> (The initial value)
#          editable: <bool> (Whether the param is editable in the editor)
#          preview: <bool> (Whether the param is editable in the editor)
#          global: (OPTIONAL) (Whether the param has a global setting available in the project settings)

Renderables:
  icon: "Content/Icons/Renderable.png"
  options:
    # Create Sprite
    - display_name: "Create Sprite"
      action_name: "create_sprite"
      requirements:
        - name: "key"
          type: "str"
          value: ""
          editable: True
          preview: True

        - name: "sprite"
          type: "file_image"
          value: "None"
          editable: True
          preview: True

        - name: "position"
          type: "vector2"
          value: [0,0]
          editable: True
          preview: True

        - name: "center_align"
          type: "bool"
          value: True
          global: 
            active: True
          editable: True
          preview: True

        - name: "flip"
          type: "bool"
          value: False
          editable: True
          preview: False

        - name: "z_order"
          type: "int"
          value: 0
          global: 
            active: True
          editable: True
          preview: True

        - name: "transition"
          type: "container"
          preview: True
          children:
            - name: "type"
              type: "dropdown"
              value: "None"
              options:
                - "None"
                - "fade_in"
              editable: True
              preview: True

            - name: "speed"
              type: "int"
              value: 500
              editable: True
              preview: True

        - name: "post_wait"
          type: "dropdown"
          value: "wait_for_input"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True
    # Create Text
    - display_name: "Create Text"
      action_name: "create_text"
      requirements:
        - name: "key"
          type: "str"
          value: ""
          editable: True
          preview: True

        - name: "position"
          type: "vector2"
          value: [0,0]
          editable: True
          preview: True

        - name: "center_align"
          type: "bool"
          value: True
          global: 
            active: True
          editable: True
          preview: False

        - name: "text"
          type: "paragraph"
          value: ""
          editable: True
          preview: True

        - name: "text_size"
          type: "int"
          value: 24
          global: 
            active: True
          editable: True
          preview: True

        - name: "text_color"
          type: "color"
          value: [255, 255, 255]
          global: 
            active: True
          editable: True
          preview: True

        - name: "font"
          type: "file_font"
          value: "None"
          global: 
            active: True
          editable: True
          preview: False

        - name: "z_order"
          type: "int"
          value: 0
          global: 
            active: True
          editable: True
          preview: True

        - name: "transition"
          type: "container"
          preview: True
          children:
            - name: "type"
              type: "dropdown"
              value: "None"
              options:
                - "None"
                - "fade_in"
              editable: True
              preview: True

            - name: "speed"
              type: "int"
              value: 500
              editable: True
              preview: True

        - name: "post_wait"
          type: "dropdown"
          value: "wait_for_input"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True
    # Create Background
    - display_name: "Create Background"
      action_name: "create_background"
      requirements:
        - name: "key"
          type: "str"
          value: "Background"
          editable: False
          preview: True

        - name: "sprite"
          type: "file_image"
          value: "None"
          editable: True
          preview: True

        - name: "position"
          type: "vector2"
          value: [0,0]
          editable: True
          preview: False

        - name: "z_order"
          type: "int"
          value: -9999
          global: 
            active: True
          editable: False
          preview: False

        - name: "post_wait"
          type: "dropdown"
          value: "no_wait"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True
    # Remove Renderable
    - display_name: "Remove Renderable"
      action_name: "remove_renderable"
      requirements:
        - name: "key"
          type: "str"
          value: ""
          editable: True
          preview: True

        - name: "transition"
          type: "container"
          preview: True
          children:
            - name: "type"
              type: "dropdown"
              value: "None"
              options:
                - "None"
                - "fade_out"
              editable: True
              preview: True

            - name: "speed"
              type: "int"
              value: 500
              editable: True
              preview: True

        - name: "post_wait"
          type: "dropdown"
          value: "no_wait"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True

Dialogue:
  icon: "Content/Icons/Dialogue.png"
  options:
    # Create Dialogue Interface
    - display_name: "Create Dialogue Interface"
      action_name: "create_dialogue_interface"
      requirements:
        - name: "sprite"
          type: "file_image"
          value: "None"
          global: 
            active: True
          editable: True
          preview: True

        - name: "position"
          type: "vector2"
          value: [0,0]
          global: 
            active: True
          editable: True
          preview: True

        - name: "center_align"
          type: "bool"
          value: True
          global: 
            active: True
          editable: True
          preview: True

        - name: "z_order"
          type: "int"
          value: 0
          global: 
            active: True
          editable: True
          preview: True
        
        - name: "post_wait"
          type: "dropdown"
          value: "no_wait"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True
        

    # Dialogue
    - display_name: "Dialogue"
      action_name: "dialogue"
      requirements:
        - name: "speaker"
          type: "container"
          preview: True
          children:
            - name: "key"
              type: "str"
              value: "SpeakerText"
              editable: False
              preview: False

            - name: "position"
              type: "vector2"
              value: [0,0]
              global: 
                active: True
              editable: True
              preview: False

            - name: "center_align"
              type: "bool"
              value: True
              global: 
                active: True
              editable: True
              preview: False

            - name: "text"
              type: "str"
              value: ""
              editable: True
              preview: True

            - name: "text_size"
              type: "int"
              value: 24
              global: 
                active: True
              editable: True
              preview: False

            - name: "text_color"
              type: "color"
              value: [255, 255, 255]
              global: 
                active: True
              editable: True
              preview: False

            - name: "font"
              type: "file_font"
              value: "None"
              global: 
                active: True
              editable: True
              preview: False

            - name: "z_order"
              type: "int"
              value: 0
              global: 
                active: True
              editable: True
              preview: False

            - name: "transition"
              type: "container"
              preview: False
              children:
                - name: "type"
                  type: "dropdown"
                  value: "None"
                  options:
                    - "fade_in"
                    - "None"
                  editable: True
                  preview: False

                - name: "speed"
                  type: "int"
                  value: 500
                  editable: True
                  preview: False

        - name: "dialogue"
          type: "container"
          preview: True
          children:
            - name: "key"
              type: "str"
              value: "DialogueText"
              editable: False
              preview: False

            - name: "position"
              type: "vector2"
              value: [0,0]
              global: 
                active: True
              editable: True
              preview: False

            - name: "center_align"
              type: "bool"
              value: True
              global: 
                active: True
              editable: True
              preview: False

            - name: "text"
              type: "paragraph"
              value: ""
              editable: True
              preview: True

            - name: "text_size"
              type: "int"
              value: 24
              global: 
                active: True
              editable: True
              preview: False

            - name: "text_color"
              type: "color"
              value: [255, 255, 255]
              global: 
                active: True
              editable: True
              preview: False

            - name: "font"
              type: "file_font"
              value: "None"
              global: 
                active: True
              editable: True
              preview: False

            - name: "z_order"
              type: "int"
              value: 0
              global: 
                active: True
              editable: True
              preview: False

            - name: "transition"
              type: "container"
              preview: False
              children:
                - name: "type"
                  type: "dropdown"
                  value: "None"
                  options:
                    - "fade_in"
                    - "None"
                  editable: True
                  preview: False

                - name: "speed"
                  type: "int"
                  value: 500
                  editable: True
                  preview: False

        - name: "post_wait"
          type: "dropdown"
          value: "wait_for_input"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True

    # Choice
    - display_name: "Choice"
      action_name: "choice"
      requirements:
        - name: "Choice"
          type: "choice"
          value: None
          editable: True
          preview: True
          template:
            - name: "type"
              type: "dropdown"
              value: "None"
              options:
                - "None"
                - "fade_in"
              editable: True
              preview: True

            - name: "speed"
              type: "int"
              value: 500
              editable: True
              preview: True

Scene:
  icon: "Content/Icons/Dialogue.png"
  options:
    # Load Scene
    - display_name: "Load Scene"
      action_name: "load_scene"
      requirements:
        - name: "scene_file"
          type: "file_data"
          value: ""
          editable: True
          preview: True
    # Fade Scene From Black
    - display_name: "Fade Scene From Black"
      action_name: "fade_scene_from_black"
      requirements:
        - name: "z_order"
          type: "int"
          value: "9999"
          global:
            active: True
          editable: True
          preview: True
        - name: "speed"
          type: "int"
          value: "150"
          global:
            active: True
          editable: True
          preview: True
        - name: "post_wait"
          type: "dropdown"
          value: "wait_until_complete"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True

#- Sound: ""
#- Effect: ""
