# Due to the way actions are designed, it's difficult to detect the data that they may require. In order to create
# a common, central place for the editor to know the requirements of each action, this file serves to list them out
#
# <category>:
#  - icon: <icon_path> (Icon in the editor content dir to use for the menu icon)
#  - options:
#    - display_name: <str> (Visible in Editor)
#      action_name: <str>> (Found in the engine actions)
#      requirements:
#       -  name: <str> (The name of the parameter)
#          type: <data_type> (A python data type)
#          default: <contextual_type> (The initial value)
#          editable: <bool> (Whether the param is editable in the editor)
#          preview: <bool> (Whether the param is editable in the editor)
#          global: (OPTIONAL) (A value in the project's Game.yaml file)
#              category: <str> (The name of the category, IE. 'Sprite')
#              global_parameter: <str> (The name of the parameter in the category, IE. 'center_align')

Renderables:
  icon: "Content/Icons/Renderable.png"
  options:
    # Create Sprite
    - display_name: "Create Sprite"
      action_name: "create_sprite"
      requirements:
        - name: "key"
          type: "str"
          value: ""
          editable: True
          preview: True

        - name: "sprite"
          type: "file_image"
          value: "None"
          editable: True
          preview: True

        - name: "position"
          type: "tuple"
          value: [0,0]
          editable: True
          preview: True

        - name: "center_align"
          type: "bool"
          value: True
          global:
            category: "Sprite"
            global_parameter: "center_align"
          editable: True
          preview: True

        - name: "flip"
          type: "bool"
          value: False
          editable: True
          preview: False

        - name: "z_order"
          type: "int"
          value: 0
          global:
            category: "Sprite"
            global_parameter: "z_order"
          editable: True
          preview: True

        - name: "transition"
          type: "container"
          preview: True
          children:
            - name: "type"
              type: "dropdown"
              value: "None"
              options:
                - "None"
                - "fade_in"
              editable: True
              preview: True

            - name: "speed"
              type: "int"
              value: 500
              editable: True
              preview: True
    # Create Text
    - display_name: "Create Text"
      action_name: "create_text"
      requirements:
        - name: "key"
          type: "str"
          value: ""
          editable: True
          preview: True

        - name: "position"
          type: "tuple"
          value: [0,0]
          editable: True
          preview: True

        - name: "center_align"
          type: "bool"
          value: True
          global:
            category: "Text"
            global_parameter: "center_align"
          editable: True
          preview: False

        - name: "text"
          type: "paragraph"
          value: ""
          editable: True
          preview: True

        - name: "text_size"
          type: "int"
          value: 24
          global:
            category: "Text"
            global_parameter: "size"
          editable: True
          preview: True

        - name: "text_color"
          type: "color"
          value: [255, 255, 255]
          global:
            category: "Text"
            global_parameter: "color"
          editable: True
          preview: True

        - name: "font"
          type: "file_font"
          value: "None"
          global:
            category: "Text"
            global_parameter: "font"
          editable: True
          preview: False

        - name: "z_order"
          type: "int"
          value: 0
          global:
            category: "Text"
            global_parameter: "z_order"
          editable: True
          preview: True

        - name: "transition"
          type: "container"
          preview: True
          children:
            - name: "type"
              type: "dropdown"
              value: "None"
              options:
                - "None"
                - "fade_in"
              editable: True
              preview: True

            - name: "speed"
              type: "int"
              value: 500
              editable: True
              preview: True
    # Create Background
    - display_name: "Create Background"
      action_name: "create_background"
      requirements:
        - name: "key"
          type: "str"
          value: "Background"
          editable: False
          preview: True

        - name: "sprite"
          type: "file_image"
          value: "None"
          editable: True
          preview: True

        - name: "position"
          type: "tuple"
          value: [0,0]
          editable: True
          preview: False

        - name: "z_order"
          type: "int"
          value: -9999 #Replace with a reference to the global setting
          global:
            category: "Sprite"
            global_parameter: "background_z_order"
          editable: False
          preview: False

Dialogue:
  icon: "Content/Icons/Dialogue.png"
  options:
    - display_name: "Dialogue"
      action_name: "dialogue"
      requirements:
        - name: "speaker"
          type: "container"
          preview: True
          children:
            - name: "key"
              type: "str"
              value: "SpeakerText"
              editable: False
              preview: False

            - name: "position"
              type: "tuple"
              value: [0,0]
              global:
                category: "Dialogue"
                global_parameter: "speaker_text_position"
              editable: True
              preview: False

            - name: "center_align"
              type: "bool"
              value: True
              global:
                category: "Dialogue"
                global_parameter: "speaker_center_align"
              editable: True
              preview: False

            - name: "text"
              type: "str"
              value: ""
              editable: True
              preview: True

            - name: "text_size"
              type: "int"
              value: 24
              global:
                category: "Dialogue"
                global_parameter: "speaker_text_size"
              editable: True
              preview: False

            - name: "text_color"
              type: "color"
              value: [255, 255, 255]
              global:
                category: "Dialogue"
                global_parameter: "speaker_text_color"
              editable: True
              preview: False

            - name: "font"
              type: "file_font"
              value: "None"
              global:
                category: "Dialogue"
                global_parameter: "speaker_font"
              editable: True
              preview: False

            - name: "z_order"
              type: "int"
              value: 0
              global:
                category: "Dialogue"
                global_parameter: "speaker_z_order"
              editable: True
              preview: False

            - name: "transition"
              type: "container"
              preview: False
              children:
                - name: "type"
                  type: "dropdown"
                  value: "None"
                  options:
                    - "fade_in"
                    - "None"
                  editable: True
                  preview: False

                - name: "speed"
                  type: "int"
                  value: 500
                  editable: True
                  preview: False

        - name: "dialogue"
          type: "container"
          preview: True
          children:
            - name: "key"
              type: "str"
              value: "DialogueText"
              editable: False
              preview: False

            - name: "position"
              type: "tuple"
              value: [0,0]
              global:
                category: "Dialogue"
                global_parameter: "dialogue_text_position"
              editable: True
              preview: False

            - name: "center_align"
              type: "bool"
              value: True
              global:
                category: "Dialogue"
                global_parameter: "dialogue_center_align"
              editable: True
              preview: False

            - name: "text"
              type: "paragraph"
              value: ""
              editable: True
              preview: True

            - name: "text_size"
              type: "int"
              value: 24
              global:
                category: "Dialogue"
                global_parameter: "dialogue_text_size"
              editable: True
              preview: False

            - name: "text_color"
              type: "color"
              value: [255, 255, 255]
              global:
                category: "Dialogue"
                global_parameter: "dialogue_text_color"
              editable: True
              preview: False

            - name: "font"
              type: "file_font"
              value: "None"
              global:
                category: "Dialogue"
                global_parameter: "dialogue_font"
              editable: True
              preview: False

            - name: "z_order"
              type: "int"
              value: 0
              global:
                category: "Dialogue"
                global_parameter: "dialogue_z_order"
              editable: True
              preview: False

            - name: "transition"
              type: "container"
              preview: False
              children:
                - name: "type"
                  type: "dropdown"
                  value: "None"
                  options:
                    - "fade_in"
                    - "None"
                  editable: True
                  preview: False

                - name: "speed"
                  type: "int"
                  value: 500
                  editable: True
                  preview: False

      #- display_name: "Choice"
      #  action_name: "choice"

#- Sound: ""
#- Effect: ""
