Renderables:
  icon: ":/Icons/AM_Renderable.png"
  options:
    - name: "create_sprite"
      applicable_editors:
        - Scene_Dialogue
        - Scene_Point_And_Click
    - name: "create_background"
      applicable_editors:
        - Scene_Dialogue
        - Scene_Point_And_Click
    - name: "create_text"
      applicable_editors:
        - Scene_Dialogue
        - Scene_Point_And_Click
    - name: "remove_renderable"
      applicable_editors:
        - Scene_Dialogue

Interactables:
  icon: ":/Icons/AM_Renderable.png"
  options:
    - name: "create_button"
      applicable_editors:
        - Scene_Point_And_Click

Dialogue:
  icon: ":/Icons/AM_Dialogue.png"
  options:
    - name: "create_dialogue_interface"
      applicable_editors:
        - Scene_Dialogue
    - name: "dialogue"
      applicable_editors:
        - Scene_Dialogue
    - name: "choice"
      applicable_editors:
        - Scene_Dialogue

Scene:
  icon: ":/Icons/AM_Scene.png"
  options:
    - name: "load_scene"
      applicable_editors:
        - Scene_Dialogue
