# Due to the way actions are designed, it's difficult to detect the data that they may require. In order to create
# a common, central place for the editor to know the requirements of each action, this file serves to list them out
#
# <category>:
#  - icon: <icon_path> (Icon in the editor content dir to use for the menu icon)
#  - options:
#    - display_name: <str> (Visible in Editor)
#      action_name: <str>> (Found in the engine actions)
#      requirements:
#       -  name: <str> (The name of the parameter)
#          type: <data_type> (A python data type)
#          default: <contextual_type> (The initial value)
#          editable: <bool> (Whether the param is editable in the editor)
#          preview: <bool> (Whether the param is editable in the editor)
#          global: (OPTIONAL) (Whether the param has a global setting available in the project settings)

Renderables:
  icon: ":/Icons/Renderable.png"
  options:
    # Create Sprite
    - display_name: "Create Sprite"
      action_name: "create_sprite"
      requirements:
        - name: "key"
          type: "String"
          value: ""
          editable: True
          preview: True

        - name: "sprite"
          type: "File_Image"
          value: "None"
          editable: True
          preview: True

        - name: "position"
          type: "Vector2"
          value: [0.5, 0.5]
          editable: True
          preview: True

        - name: "center_align"
          type: "Bool"
          value: True
          global: 
            active: True
          editable: True
          preview: True

        - name: "flip"
          type: "Bool"
          value: False
          editable: True
          preview: False

        - name: "z_order"
          type: "Int"
          value: 0
          global: 
            active: True
          editable: True
          preview: True

        - name: "transition"
          type: "Container"
          preview: True
          children:
            - name: "type"
              type: "Dropdown"
              value: "None"
              options:
                - "None"
                - "fade_in"
              editable: True
              preview: True

            - name: "speed"
              type: "Int"
              value: 500
              editable: True
              preview: True

        - name: "post_wait"
          type: "Dropdown"
          value: "wait_for_input"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True
    # Create Text
    - display_name: "Create Text"
      action_name: "create_text"
      requirements:
        - name: "key"
          type: "String"
          value: ""
          editable: True
          preview: True

        - name: "position"
          type: "Vector2"
          value: [0.5,0.5]
          editable: True
          preview: True

        - name: "center_align"
          type: "Bool"
          value: True
          global: 
            active: True
          editable: True
          preview: False

        - name: "text"
          type: "Paragraph"
          value: ""
          editable: True
          preview: True

        - name: "text_size"
          type: "Int"
          value: 24
          global: 
            active: True
          editable: True
          preview: True

        - name: "text_color"
          type: "Color"
          value: [255, 255, 255]
          global: 
            active: True
          editable: True
          preview: True

        - name: "font"
          type: "File_Font"
          value: "None"
          global: 
            active: True
          editable: True
          preview: False

        - name: "z_order"
          type: "Int"
          value: 0
          global: 
            active: True
          editable: True
          preview: True

        - name: "wrap_bounds"
          type: "Vector2"
          value: [0.2,0.2]
          global:
            active: True
          editable: True
          preview: False

        - name: "transition"
          type: "Container"
          preview: True
          children:
            - name: "type"
              type: "Dropdown"
              value: "None"
              options:
                - "None"
                - "fade_in"
              editable: True
              preview: True

            - name: "speed"
              type: "Int"
              value: 500
              editable: True
              preview: True

        - name: "post_wait"
          type: "Dropdown"
          value: "wait_for_input"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True
    # Create Background
    - display_name: "Create Background"
      action_name: "create_background"
      requirements:
        - name: "key"
          type: "String"
          value: "Background"
          editable: False
          preview: True

        - name: "sprite"
          type: "File_Image"
          value: "None"
          editable: True
          preview: True

        - name: "position"
          type: "Vector2"
          value: [0,0]
          editable: True
          preview: False

        - name: "z_order"
          type: "Int"
          value: -9999
          global:
            active: True
          editable: True
          preview: False

        - name: "post_wait"
          type: "Dropdown"
          value: "no_wait"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True
    # Remove Renderable
    - display_name: "Remove Renderable"
      action_name: "remove_renderable"
      requirements:
        - name: "key"
          type: "String"
          value: ""
          editable: True
          preview: True

        - name: "transition"
          type: "Container"
          preview: True
          children:
            - name: "type"
              type: "Dropdown"
              value: "None"
              options:
                - "None"
                - "fade_out"
              editable: True
              preview: True

            - name: "speed"
              type: "Int"
              value: 500
              editable: True
              preview: True

        - name: "post_wait"
          type: "Dropdown"
          value: "no_wait"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True

Dialogue:
  icon: ":/Icons/Dialogue.png"
  options:
    # Create Dialogue Interface
    - display_name: "Create Dialogue Interface"
      action_name: "create_dialogue_interface"
      requirements:
        - name: "sprite"
          type: "File_Image"
          value: "None"
          global: 
            active: True
          editable: True
          preview: True

        - name: "position"
          type: "Vector2"
          value: [0,0]
          global: 
            active: True
          editable: True
          preview: True

        - name: "center_align"
          type: "Bool"
          value: True
          global: 
            active: True
          editable: True
          preview: True

        - name: "z_order"
          type: "Int"
          value: 0
          global: 
            active: True
          editable: True
          preview: True
        
        - name: "post_wait"
          type: "Dropdown"
          value: "no_wait"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True
        

    # Dialogue
    - display_name: "Dialogue"
      action_name: "dialogue"
      requirements:
        - name: "speaker"
          type: "Container"
          preview: True
          children:
            - name: "key"
              type: "String"
              value: "SpeakerText"
              editable: False
              preview: False

            - name: "position"
              type: "Vector2"
              value: [0,0]
              global: 
                active: True
              editable: True
              preview: False

            - name: "center_align"
              type: "Bool"
              value: True
              global: 
                active: True
              editable: True
              preview: False

            - name: "text"
              type: "String"
              value: ""
              editable: True
              preview: True

            - name: "text_size"
              type: "Int"
              value: 24
              global: 
                active: True
              editable: True
              preview: False

            - name: "text_color"
              type: "Color"
              value: [255, 255, 255]
              global: 
                active: True
              editable: True
              preview: False

            - name: "font"
              type: "File_Font"
              value: "None"
              global: 
                active: True
              editable: True
              preview: False

            - name: "z_order"
              type: "Int"
              value: 0
              global: 
                active: True
              editable: True
              preview: False

            - name: "transition"
              type: "Container"
              preview: False
              children:
                - name: "type"
                  type: "Dropdown"
                  value: "None"
                  options:
                    - "fade_in"
                    - "None"
                  editable: True
                  preview: False

                - name: "speed"
                  type: "Int"
                  value: 500
                  editable: True
                  preview: False

        - name: "dialogue"
          type: "Container"
          preview: True
          children:
            - name: "key"
              type: "String"
              value: "DialogueText"
              editable: False
              preview: False

            - name: "position"
              type: "Vector2"
              value: [0,0]
              global: 
                active: True
              editable: True
              preview: False

            - name: "center_align"
              type: "Bool"
              value: True
              global:
                active: True
              editable: True
              preview: False

            - name: "text"
              type: "Paragraph"
              value: ""
              editable: True
              preview: True

            - name: "text_size"
              type: "Int"
              value: 24
              global: 
                active: True
              editable: True
              preview: False

            - name: "text_color"
              type: "Color"
              value: [255, 255, 255]
              global: 
                active: True
              editable: True
              preview: False

            - name: "font"
              type: "File_Font"
              value: "None"
              global: 
                active: True
              editable: True
              preview: False

            - name: "z_order"
              type: "Int"
              value: 0
              global: 
                active: True
              editable: True
              preview: False

            - name: "transition"
              type: "Container"
              preview: False
              children:
                - name: "type"
                  type: "Dropdown"
                  value: "None"
                  options:
                    - "fade_in"
                    - "None"
                  editable: True
                  preview: False

                - name: "speed"
                  type: "Int"
                  value: 500
                  editable: True
                  preview: False

        - name: "post_wait"
          type: "Dropdown"
          value: "wait_for_input"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True

    # Choice
    - display_name: "Choice"
      action_name: "choice"
      requirements:
        - name: "choices"
          type: "Array"
          editable: True
          preview: True
          template:
            name: "choice"
            type: "Array_Element"
            preview: True
            children:
              - name: "branch"
                type: "String"
                value: ""
                editable: True
                preview: True
              - name: "position"
                type: "Vector2"
                value: [ 0,0 ]
                editable: True
                preview: False

              - name: "text"
                type: "String"
                value: ""
                editable: True
                preview: True

              - name: "text_size"
                type: "Int"
                value: 24
                global:
                  active: True
                editable: True
                preview: False

              - name: "text_color"
                type: "Color"
                value: [ 255, 255, 255 ]
                global:
                  active: True
                editable: True
                preview: False

              - name: "font"
                type: "File_Font"
                value: "None"
                global:
                  active: True
                editable: True
                preview: False

              - name: "z_order"
                type: "Int"
                value: 0
                global:
                  active: True
                editable: True
                preview: False

Scene:
  icon: ":/Icons/Dialogue.png"
  options:
    # Load Scene
    - display_name: "Load Scene"
      action_name: "load_scene"
      requirements:
        - name: "scene_file"
          type: "File_Data"
          value: ""
          editable: True
          preview: True
    # Fade Scene From Black
    - display_name: "Fade Scene From Black"
      action_name: "fade_scene_from_black"
      requirements:
        - name: "z_order"
          type: "Int"
          value: "9999"
          global:
            active: True
          editable: True
          preview: True

        - name: "speed"
          type: "Int"
          value: "150"
          global:
            active: True
          editable: True
          preview: True

        - name: "post_wait"
          type: "Dropdown"
          value: "wait_until_complete"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True

Sound:
  icon: ":/Icons/Dialogue.png"
  options:
    # Play SFX
    - display_name: "Play SFX"
      action_name: "play_sfx"
      requirements:
        - name: "key"
          type: "String"
          value: ""
          editable: True
          preview: True

        - name: "sound"
          type: "File_Sound"
          value: ""
          editable: True
          preview: True

        - name: "volume"
          type: "Float"
          value: 1.0
          editable: True
          preview: True

        - name: "post_wait"
          type: "Dropdown"
          value: "wait_until_complete"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True

    # Play Music
    - display_name: "Play Music"
      action_name: "play_music"
      requirements:
        - name: "music"
          type: "File_Sound"
          value: ""
          editable: True
          preview: True

        - name: "volume"
          type: "Float"
          value: 1.0
          editable: True
          preview: True

        - name: "loop"
          type: "Bool"
          value: False
          editable: True
          preview: True

        - name: "post_wait"
          type: "Dropdown"
          value: "no_wait"
          options:
            - "no_wait"
            - "wait_for_input"
            - "wait_until_complete"
          editable: True
          preview: True

    # Stop SFX
    - display_name: "Stop SFX"
      action_name: "stop_sfx"
      requirements:
        - name: "key"
          type: "String"
          value: ""
          editable: True
          preview: True

    # Stop Music
    - display_name: "Stop Music"
      action_name: "stop_music"
      requirements:
        - name: "key"
          type: "String"
          value: ""
          editable: True
          preview: True

Utilities:
  icon: ":/Icons/Dialogue.png"
  options:
    # Wait
    - display_name: "Wait"
      action_name: "wait"
      requirements:
        - name: "seconds"
          type: "Int"
          value: 3
          editable: True
          preview: True
        - name: "post_wait"
          type: "Dropdown"
          value: "wait_until_complete"
          options:
            - "wait_until_complete"
          editable: False
          preview: False
