Renderables:
  icon: ":/Icons/AM_Renderable.png"
  options:
    - name: "create_sprite"
      applicable_editors:
        - Scene_Dialogue
        - Scene_Point_And_Click
        - Interface
    - name: "create_background"
      applicable_editors:
        - Scene_Dialogue
        - Scene_Point_And_Click
        - Interface
    - name: "create_text"
      applicable_editors:
        - Scene_Dialogue
        - Scene_Point_And_Click
        - Interface
    - name: "remove_renderable"
      applicable_editors:
        - Scene_Dialogue

Interactables:
  icon: ":/Icons/AM_Renderable.png"
  options:
    - name: "create_button"
      applicable_editors:
        - Scene_Point_And_Click
        - Interface
    - name: "create_text_button"
      applicable_editors:
        - Scene_Point_And_Click
        - Interface

Dialogue:
  icon: ":/Icons/AM_Dialogue.png"
  options:
    - name: "dialogue"
      applicable_editors:
        - Scene_Dialogue
    - name: "choice"
      applicable_editors:
        - Scene_Dialogue

Scene:
  icon: ":/Icons/AM_Scene.png"
  options:
    - name: "load_scene"
      applicable_editors:
        - Scene_Dialogue
    - name: "scene_fade_in"
      applicable_editors:
        - Scene_Dialogue
    - name: "scene_fade_out"
      applicable_editors:
        - Scene_Dialogue

Sound:
  icon: ":/Icons/AM_Dialogue.png"
  options:
    - name: "play_sfx"
      applicable_editors:
        - Scene_Dialogue
    - name: "play_music"
      applicable_editors:
        - Scene_Dialogue
    - name: "stop_sfx"
      applicable_editors:
        - Scene_Dialogue
    - name: "stop_music"
      applicable_editors:
        - Scene_Dialogue
    - name: "set_mute"
      applicable_editors:
        - Scene_Dialogue
        - Scene_Point_And_Click
