EditorSettings:
  version: 0.1
  version_string: Created with Heartbeat Editor v0.1
  max_tabs: 3
  active_theme: "EditorContent:Themes/Dark/Dark.css"
  active_fonts:
    - "EditorContent:Fonts/Cabin/Cabin-Regular.ttf"
    - "EditorContent:Fonts/Cabin/Cabin-Medium.ttf"
    - "EditorContent:Fonts/Cabin/Cabin-MediumItalic.ttf"
    - "EditorContent:Fonts/Cabin/Cabin-Bold.ttf"
    - "EditorContent:Fonts/Cabin/Cabin-BoldItalic.ttf"
    - "EditorContent:Fonts/Cabin/Cabin-SemiBold.ttf"
    - "EditorContent:Fonts/Cabin/Cabin-SemiBoldItalic.ttf"
Outliner:
  icon_size:
    - 40
    - 40