EditorSettings:
  version: 0.1
  version_string: Created with Heartbeat Editor v0.1
  max_tabs: 3
  theme: ":/Themes/Dark.css"
  fonts:
    - ":/Fonts/Comfortaa-Regular.ttf"
    - ":/Fonts/Comfortaa-Light.ttf"
    - ":/Fonts/Comfortaa-Bold.ttf"
