EditorInterfaceSettings:
  toolbar_background_color: 44, 53, 57
  toolbar_button_background_color: 57, 67, 79
  general_button_background_color: 217, 217, 217
  general_button_border_color: 96, 96, 96

EditorStateSettings:
  read_only_background_color: 200, 200, 200
  selection_color: 180, 218, 244

EditorTextSettings:
  header_1_font: "Helvetica"
  header_1_text_size: 12
  header_1_color: 44,53,57
  header_1_is_bold: True
  header_1_is_italicized: False

  header_2_font: "Helvetica"
  header_2_text_size: 11
  header_2_color: 44,53,57
  header_2_is_bold: False
  header_2_is_italicized: False

  paragraph_font: "Helvetica"
  paragraph_text_size: 8
  paragraph_color: 0, 0, 0
  paragraph_is_bold: False
  paragraph_is_italicized: False

  subtext_font: "Helvetica"
  subtext_text_size: 8
  subtext_color: 96, 96, 96
  subtext_is_bold: False
  subtext_is_italicized: True

  editor_info_title_font: "Helvetica"
  editor_info_title_text_size: 16
  editor_info_title_color: 96, 96, 96
  editor_info_title_is_bold: False
  editor_info_title_is_italicized: False

  editor_info_paragraph_font: "Helvetica"
  editor_info_paragraph_text_size: 8
  editor_info_paragraph_color: 96, 96, 96
  editor_info_paragraph_is_bold: False
  editor_info_paragraph_is_italicized: False

  button_font: "Helvetica"
  button_text_size: 10
  button_color: 0, 0, 0
  button_is_bold: False
  button_is_italicized: False

  log_font: "Helvetica"
  log_text_size: 10
  log_normal_color: 0, 0, 0
  log_success_color: 51, 153, 0
  log_warning_color: 255, 204, 0
  log_error_color: 204, 51, 0
