# This file is used to define the types of all settings in a Heartbeat Project file using the 'ParameterType' enum.
# Traditionally, a 'TypedDict' would be preferred over using this approach, but since we use non-standard types such
# as 'file_image', 'paragraph', etc, we can't rely on raw Python data types

# Whenever a new setting is added to the project file (Ideally propagating back to the 'DefaultGame' file), this file
# should be updated as well

Game:
  title: "String"
  author: "String"
  company: "String"
  starting_scene: "Asset_Scene"

Window:
  resolution: "" # This is generated when choosing a value for 'resolution_options'
  resolution_options: "CUST_Resolution"

Text:
  size: "Int"
  color: "Color"
  font: "Asset_Font"
  z_order: "Int"
  center_align: "Bool"
  wrap_bounds: "Vector2"

Button:
  sprite: "Asset_Image"
  sprite_hover: "Asset_Image"
  sprite_clicked: "Asset_Image"
  z_order: "Int"
  font: "Asset_Font"

Dialogue:
  transition_type: "String"  # TODO: Figure out how to support a Dropdown type here (Game.yaml doesn't have any way of specifying the 'options' yet
  transition_speed: "Int"
  text_speed: "Int"
  speaker_text_position: "Vector2"
  speaker_text_size: "Int"
  speaker_text_color: "Color"
  speaker_text_font: "Asset_Font"
  speaker_text_z_order: "Int"
  speaker_text_center_align: "Bool"
  speaker_text_wrap_bounds: "Vector2"
  dialogue_text_position: "Vector2"
  dialogue_text_size: "Int"
  dialogue_text_color: "Color"
  dialogue_text_font: "Asset_Font"
  dialogue_text_z_order: "Int"
  dialogue_text_center_align: "Bool"
  dialogue_text_wrap_bounds: "Vector2"
  dialogue_frame_sprite: "Asset_Image"
  dialogue_frame_z_order: "Int"
  dialogue_frame_center_align: "Bool"
  dialogue_frame_position: "Vector2"
  choice_button_sprite: "Asset_Image"
  choice_button_sprite_hover: "Asset_Image"
  choice_button_sprite_clicked: "Asset_Image"
  choice_button_z_order: "Int"
  choice_button_center_align: "Bool"
  choice_button_text_size: "Int"
  choice_button_text_color: "Color"
  choice_button_text_color_hover: "Color"
  choice_button_text_color_clicked: "Color"
  choice_button_font: "Asset_Font"

Pause Menu:
  data_file: "Asset_Data"

Scene Transitions:
  speed: "Int"
  z_order: "Int"

